# Generated by Django 5.1.2 on 2024-10-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamaZZZ', '0002_alter_items_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_pic',
            field=models.ImageField(blank=True, default='../upload/Default_pic.png', null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_pic',
            field=models.ImageField(blank=True, default='../upload/Default_pic.png', null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, default='../upload/Default_pic.png', null=True, upload_to='upload'),
        ),
    ]
