# Generated by Django 5.1.2 on 2024-10-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamaZZZ', '0003_alter_design_design_pic_alter_items_item_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_pic',
            field=models.ImageField(blank=True, default='../upload/Default_pic.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, default='../upload/Default_pic.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_pic',
            field=models.ImageField(blank=True, default='../upload/Default_pic.png', null=True, upload_to='images/'),
        ),
    ]
