# Generated by Django 5.1.2 on 2024-11-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamaZZZ', '0010_remove_items_id_remove_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductWomen',
        ),
    ]
