# Generated by Django 5.1.2 on 2024-11-10 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamaZZZ', '0011_rename_product_productwomen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_pic', models.ImageField(blank=True, default='images/Default_pic.jpg', null=True, upload_to='images/')),
                ('product_price', models.FloatField()),
                ('product_category', models.CharField(max_length=200)),
                ('product_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('type_of_product', models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10, null=True)),
            ],
        ),
    ]
