# Generated by Django 5.1.2 on 2024-11-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamaZZZ', '0017_cart_is_paid_cart_user_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='pro_m',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='pro_w',
        ),
    ]
