# Generated by Django 5.1.2 on 2024-11-22 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamaZZZ', '0018_remove_cartitems_pro_m_remove_cartitems_pro_w'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(blank=True, default='+880', max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, default='static/images/default_no_img.jfif', null=True, upload_to='static/images')),
                ('about_myself', models.TextField(blank=True, default='will add later', null=True)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
