# Generated by Django 5.1.2 on 2024-11-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamaZZZ', '0020_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nid',
            field=models.CharField(default='12345', max_length=5),
        ),
    ]
