# Generated by Django 5.1.2 on 2024-11-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamaZZZ', '0022_remove_cart_create_date_remove_cart_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('shipping_address', models.TextField(max_length=200)),
                ('payment_method', models.CharField(blank=True, choices=[('bkash', 'bkash'), ('bank', 'bank'), ('nagad', 'nagad'), ('COD', 'COD'), ('rocket', 'rocket')], default='COD', max_length=30, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jamaZZZ.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
