# Generated by Django 5.1.2 on 2024-11-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamaZZZ', '0024_order_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pic',
        ),
    ]
